### ISSUE TITLE
How to get Uri of saved Image?

### ISSUE THREAD

**Issue by kateile** [ihimanshurawat/ImageWorker#3]
Is there any simple way?

**Comment by ihimanshurawat** [comment]
umm yes.

In Kotlin it would be something like this ->
val file = File("${Environment.getExternalStorageDirectory().absolutePath}/Your Directory/Your Sub Directory/Your File Name . Your Selected Extension")

then val uri = Uri.parse(file)

Similarly in Java ->
File file = new File("${Environment.getExternalStorageDirectory().absolutePath}/Your Directory/Your Sub Directory/Your File Name . Your Selected Extension");
if(file.exists()){
      Uri uri = Uri.parse(file);
}


Note - use the Directory, Sub Directory, File Name and Extension similar to what you are saving to the directory otherwise. File will be a null object.

Note 2 - Also check out about File Provider for Nougat above while sharing the Uri in intent.

Hope it helps. Sorry for delayed reply.

**Comment by kateile** [comment]
Thanks @1AboveAll
